name: Node CI

on: [push]

jobs:
  build:

    strategy:
      matrix:
        node: [18, 24]
        os: [macos-latest, ubuntu-latest]

    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v6
    - name: Use Node.js ${{ matrix.node }} on ${{ matrix.os }}
      uses: actions/setup-node@v6
      with:
        node-version: ${{ matrix.node }}
    - name: npm install and test
      run: |
        npm install
        npm test
      env:
        CI: true
